//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public Cuenta()
        {
            this.Gastos = new HashSet<Gasto>();
            this.Ingresos = new HashSet<Ingreso>();
        }
    
        public int IdCuenta { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Balance { get; set; }
    
        public virtual ICollection<Gasto> Gastos { get; set; }
        public virtual ICollection<Ingreso> Ingresos { get; set; }
    }
}
