//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanzasPersonalesDBEntities1 : DbContext
    {
        public FinanzasPersonalesDBEntities1()
            : base("name=FinanzasPersonalesDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clasificacione> Clasificaciones { get; set; }
        public virtual DbSet<Cuenta> Cuentas { get; set; }
        public virtual DbSet<Gasto> Gastos { get; set; }
        public virtual DbSet<Ingreso> Ingresos { get; set; }
        public virtual DbSet<Presupuesto> Presupuestoes { get; set; }
        public virtual DbSet<PresupuestoDetalle> PresupuestoDetalles { get; set; }
        public virtual DbSet<SubClasificacione> SubClasificaciones { get; set; }
        public virtual DbSet<Transferencia> Transferencias { get; set; }
    }
}
