//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        public int IdGasto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public Nullable<int> IdSubClas { get; set; }
        public string Concepto { get; set; }
        public Nullable<double> Monto { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual SubClasificacione SubClasificacione { get; set; }
    }
}
