//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencia
    {
        public int IdTransferecia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdCuentaOrigen { get; set; }
        public Nullable<int> IdCuentaDestino { get; set; }
        public string Concepto { get; set; }
        public Nullable<double> Valor { get; set; }
    }
}
